"""API commands - Interact with Classic Models API."""

import click
import sys
from pathlib import Path

from cmcli.utils.logging import get_logger
from cmcli.config import get_config
from cmcli.api.client import ClassicModelsClient, ClassicModelsAPIError
from cmcli.api.updater import APIUpdater

logger = get_logger("commands.api")


@click.group()
def api():
    """Interact with the Classic Models API.
    
    Commands for verifying API connectivity and updating data in the
    Classic Models API database.
    """
    pass


@api.command()
@click.pass_context
def verify(ctx):
    """Verify API connection and authentication.
    
    Tests connectivity to the Classic Models API and validates credentials.
    """
    try:
        logger.info("Verifying Classic Models API connection...")
        
        # Load configuration
        config = get_config()
        cm_config = config.classic_models
        
        # Create client
        client = ClassicModelsClient(cm_config)
        
        # Verify connection
        client.verify_connection()
        
        logger.info("✓ API connection verified successfully!")
        logger.info(f"  API URL: {cm_config.api_url}")
        logger.info(f"  Username: {cm_config.username}")
        logger.info(f"  SSL Verification: {'Enabled' if cm_config.verify_ssl else 'Disabled'}")
        
        # Logout
        client.logout()
        
    except ValueError as e:
        logger.error(f"Configuration error: {e}")
        logger.error("Please check your .env file and ensure all required variables are set.")
        sys.exit(1)
    except ClassicModelsAPIError as e:
        logger.error(f"API error: {e}")
        sys.exit(1)
    except Exception as e:
        logger.error(f"Unexpected error: {e}")
        if ctx.obj.verbose:
            logger.exception("Full traceback:")
        sys.exit(1)


@api.command()
@click.option(
    "--dry-run",
    is_flag=True,
    help="Preview changes without actually updating the API",
)
@click.option(
    "--orders-only",
    is_flag=True,
    help="Only update orders (skip payments)",
)
@click.option(
    "--payments-only",
    is_flag=True,
    help="Only update payments (skip orders)",
)
@click.pass_context
def update_timestamps(ctx, dry_run: bool, orders_only: bool, payments_only: bool):
    """Update timestamps in the Classic Models API.
    
    Reads transformed data from JSON files (generated by 'cmcli update')
    and pushes the updates to the Classic Models API database.
    
    This updates:
    - Order dates (orderDate, requiredDate, shippedDate)
    - Payment dates (paymentDate)
    
    The JSON files must exist before running this command. Run 'cmcli update'
    first to generate them with current timestamps.
    """
    if orders_only and payments_only:
        logger.error("Cannot specify both --orders-only and --payments-only")
        sys.exit(1)
    
    try:
        # Load configuration
        config = get_config()
        cm_config = config.classic_models
        json_dir = config.json_dir
        
        # Check if JSON directory exists
        if not json_dir.exists():
            logger.error(f"JSON directory not found: {json_dir}")
            logger.error("Please run 'cmcli update' first to generate JSON files.")
            sys.exit(1)
        
        # Create client
        client = ClassicModelsClient(cm_config)
        
        # Create updater
        updater = APIUpdater(client, json_dir)
        
        # Run update
        stats = updater.run(
            dry_run=dry_run,
            orders_only=orders_only,
            payments_only=payments_only
        )
        
        # Exit with error if any updates failed
        total_failed = stats.get("orders_failed", 0) + stats.get("payments_failed", 0)
        if total_failed > 0:
            logger.warning(f"Completed with {total_failed} failures")
            sys.exit(1)
        
    except ValueError as e:
        logger.error(f"Configuration error: {e}")
        logger.error("Please check your .env file and ensure all required variables are set.")
        sys.exit(1)
    except FileNotFoundError as e:
        logger.error(str(e))
        sys.exit(1)
    except ClassicModelsAPIError as e:
        logger.error(f"API error: {e}")
        sys.exit(1)
    except Exception as e:
        logger.error(f"Unexpected error: {e}")
        if ctx.obj.verbose:
            logger.exception("Full traceback:")
        sys.exit(1)


# Made with Bob